site_name: Kinder Uni - Embedded Computer

nav:
  - Home: index.md
  - Infos:
    - info_way.md 
    - info_material.md 
  - Lektionen:
    - lessons/10_hello_world/lesson.md
    - lessons/20_dice/lesson.md
    - lessons/30_level/lesson.md
    - lessons/40_gravity/lesson.md
    - lessons/50_alarm/lesson.md
    - lessons/60_firefly/lesson.md
  - links.md

#theme: readthedocs
