site_name: Kinder Uni - Embedded Computer

nav:
  - Home: index.md
  - Infos:
    - info_way.md 
    - info_material.md 
  - Lektionen:
    - lessons/10_hello_world/lesson.md
  - links.md

#theme: readthedocs
